app = "jeff-edgewise"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 2
  processes = ["app"]

[http_service.concurrency]
  type = "connections"
  soft_limit = 50
  hard_limit = 80

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256


